version: '3.7'

services:

  casacoding_back_dev:
    container_name: casacoding_back_dev
    build:
      context: ./casacoding-back
      dockerfile: Dockerfile.development
    ports:
      - '8080:8080'
    networks:
      - casacoding
    stdin_open: true
    tty: true
  
  
  casacoding_front_dev:
    container_name: casacoding_front_dev
    build:
      context: ./casacoding-front
      dockerfile: Dockerfile.development
    ports:
      - '8081:8081'
    networks:
      - casacoding

volumes:
  data:
    driver: local

networks:
  casacoding:
    driver: bridge